//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanleWebsite
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BanleShopEntities : DbContext
    {
        public BanleShopEntities()
            : base("name=BanleShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agency> Agencies { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<ColorProductDetail> ColorProductDetails { get; set; }
        public virtual DbSet<EventBackToSchool_Color> EventBackToSchool_Color { get; set; }
        public virtual DbSet<EventBackToSchool_Order> EventBackToSchool_Order { get; set; }
        public virtual DbSet<EventBackToSchool_Pattern> EventBackToSchool_Pattern { get; set; }
        public virtual DbSet<EventBackToSchool_ShirtType> EventBackToSchool_ShirtType { get; set; }
        public virtual DbSet<EventBackToSchool_Size> EventBackToSchool_Size { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Size> Sizes { get; set; }
        public virtual DbSet<SizeProductDetail> SizeProductDetails { get; set; }
    }
}
